[project]
name = "dashboard-monitoring"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "cloudscraper>=1.2.71",
    "confluent-kafka>=2.14.0",
    "deep-translator>=1.11.4",
    "faker>=40.12.0",
    "httpx>=0.28.1",
    "jmespath>=1.1.0",
    "loguru>=0.7.3",
    "lxml>=6.0.2",
    "minio>=7.2.20",
    "openpyxl>=3.1.5",
    "pandas>=3.0.2",
    "pymongo>=4.17.0",
    "python-dotenv==1.0.1",
    "requests>=2.31.0",
    "scikit-learn>=1.8.0",
    "tldextract>=5.3.1",
    "trafilatura>=2.0.0",
    "transformers>=4.40.0",
    "yfinance>=1.4.0",
    "aiohttp>=3.13.5",
    "nltk>=3.9.4",
    "sqlalchemy>=2.0.50",
    "fastapi>=0.136.3",
    "asyncpg>=0.31.0",
    "alembic>=1.18.4",
    "psycopg2-binary==2.9.12",
    "pydantic-settings>=2.14.1",
    "python-dateutil>=2.9.0.post0",
    "uvicorn>=0.49.0",
    "apscheduler>=3.11.2",
]
